### ISSUE TITLE
Problem with @Generated annotation when upgrading jakarta-annotation-api to version 2.x

### ISSUE THREAD

**Issue by ferblaca** [xolstice/protobuf-maven-plugin#109]
When generating code from a .proto contract in Java, the `@Generated` annotation belonging to the `javax.annotation` package of the `jakarta.annotation:jakarta.annotation-api:1.x.x` library is added. For example:

```
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.50.0)",
    comments = "Source: product.proto")
@io.grpc.stub.annotations.GrpcGenerated
public final class ProductEndPointGrpc {
...
```

When updating our projects to version 2.x of the `jakarta.annotation:jakarta.annotation-api` library, the `javax.annotation` package no longer exists, it is now `jakarta.annotation`, so the autogenerated code through the plugin does not work correctly.

It would be great if the plugin could be configured to be resilient to this kind of changes.

**Comment by hatahet** [comment]
I think this is an issue with [grpc-java](https://github.com/grpc/grpc-java/issues/6833).
