### ISSUE TITLE
glibc2.14 required by protoc 3.1.0

### ISSUE THREAD

**Issue by PhantomThief** [xolstice/protobuf-maven-plugin#12]
when I upgrade protoc to 3.1.0, the error appeared:

/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/data/jenkins/workspace/****/target/protoc-plugins/protoc-3.1.0-linux-x86_64.exe)

while I cannot upgrade glibc to 2.14. It worked on protoc 3.0.2 and earlier.

**Comment by sergei-ivanov** [comment]
This is not a maven plugin issue. Please raise it with Google protobuf team.
