### ISSUE TITLE
Protocol Buffers always recompile even when nothing changed

### ISSUE THREAD

**Issue by dminkovsky** [xolstice/protobuf-maven-plugin#17]
First: thank you for this plugin!

I am wondering: is there a way to prevent this plugin for compiling on every build, even when nothing changed? Because that is what happens for me. Not sure why.

**Comment by sergei-ivanov** [comment]
Hi,

Yes, there is a mechanism for that. It is off by default (for reasons lost to the history), but it can be easily activated. Please check out the [usage page](https://www.xolstice.org/protobuf-maven-plugin/usage.html), _Suppressing Compilation Of Unchanged Definitions_ section.

Best wishes,
Sergei

**Comment by dminkovsky** [comment]
Oh that is great to see. Sorry I missed that (I did look). Thank you.
