### ISSUE TITLE
can not found symbol  OneofDescriptor

### ISSUE THREAD

**Issue by shanghai-Jerry** [xolstice/protobuf-maven-plugin#24]
how to fix this error: can not found symbol OneofDescriptor in com.google.protobuf.Descriptors

**Comment by sergei-ivanov** [comment]
Can you please provide more details.
Where are you seeing the error, steps to recreate, versions of protoc, maven and protobuf-maven-plugin. A small sample project might be needed too.
https://www.xolstice.org/protobuf-maven-plugin/contributions.html#Reporting_bugs

**Comment by sergei-ivanov** [comment]
Closing due to a lack of feedback
