### ISSUE TITLE
unable to resolve google.protobuf.Empty

### ISSUE THREAD

**Issue by mgenov** [xolstice/protobuf-maven-plugin#28]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### protoc version
libprotoc 3.3.0

### Properties

```xml
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <kotlin.version>1.1.2-5</kotlin.version>
    <grpc.version>1.4.0</grpc.version><!-- CURRENT_GRPC_VERSION -->
  </properties>
```

### Plugin definition
```xml
  <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.5.0</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.3.0:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
Extensions
```xml
<build>
 <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.4.1.Final</version>
      </extension>
    </extensions>
   ....
</build>
```

### What did you do?
mvn clean compile

### What did you expect to see?
BUILD SUCCESS

### What did you see instead?
[INFO] Compiling 2 proto file(s) to ..../target/generated-sources/protobuf/java
[ERROR] PROTOC FAILED: myservice.proto:40:59: "google.protobuf.Empty" is not defined.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

I'm I able to resolve it or I have to define my own Empty message ? 

**Note** that the google.api.http type is resolved successfully.

**Comment by sergei-ivanov** [comment]
Hello Miroslav,

A quick check: is `com.google.protobuf:protobuf-java` included in your compile dependencies? This is where `google.protobuf.Empty` is packaged.

Kind regards,
Sergei

**Comment by mgenov** [comment]
I've tried version 3.0.0 and 3.3.1 and it doesn't resolve the issue. This is how my dependency tree looks:  

<img width="554" alt="screen shot 2017-06-26 at 7 37 29 am" src="https://user-images.githubusercontent.com/209223/27524962-7791d00a-5a42-11e7-9748-069d8d0c0a66.png">

**Comment by sergei-ivanov** [comment]
Can you reproduce it in a small-scale sample project?
I am pretty sure something trivial is missing from your configuration, but I do not have enough information to tell what it is exactly.

**Comment by mgenov** [comment]
It was a silly mistake. I've forgot to include the import path in my proto definition: 

```protobuf
import "google/protobuf/empty.proto";
```

and this was the cause. 

Thanks for your feedback @sergei-ivanov

**Comment by sergei-ivanov** [comment]
I suspected something like that :)
I am glad your issue has been resolved.
