### ISSUE TITLE
Multiple package definitions.

### ISSUE THREAD

**Issue by magick93** [xolstice/protobuf-maven-plugin#33]
Am trying to generate java classes from protoc files, and get this error:

`Multiple package definitions.`

The proto file looks like:

```
syntax = "proto3";	
option java_package = "io.myco.message";
package myco;	
message UserRecordUpdateResponseMessage {

int32 int = 1;
}
```
From my understanding the protoc file is valid.

**Comment by sergei-ivanov** [comment]
This is not a maven plugin error, it is a protoc error. Have you tried compiling your proto file with a command line protoc? I wonder if the error is going to go away if you put the `package` instruction before the `option java_package`?

**Comment by magick93** [comment]
I didnt try changing the order. I instead removed the `java_package` statement, and the error is now gone.
