### ISSUE TITLE
Only getting OuterClasses - no service classes generated

### ISSUE THREAD

**Issue by magick93** [xolstice/protobuf-maven-plugin#35]
Hello
When I generate, using the following, I am not getting any service stubs generated. I only get OuterClasses.

```
<extensions>
			<extension>
				<groupId>kr.motd.maven</groupId>
				<artifactId>os-maven-plugin</artifactId>
				<version>1.4.1.Final</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.xolstice.maven.plugins</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
				<version>0.5.0</version>
				<configuration>
					<clearOutputDirectory>false</clearOutputDirectory>
					<protocArtifact>com.google.protobuf:protoc:3.4.0:exe:${os.detected.classifier}</protocArtifact>
					<pluginId>grpc-java</pluginId>
					<pluginArtifact>io.grpc:protoc-gen-grpc-java:1.6.1:exe:${os.detected.classifier}</pluginArtifact>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>compile-custom</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
```

Any idea what I am doing wrong?

**Comment by sergei-ivanov** [comment]
The configuration looks OK to me. Can you provide a complete example as a gist?

**Comment by magick93** [comment]
Hi @sergei-ivanov 

I am still working on getting a sample together.

In the meantime, perhaps you can help me understanding something. Why is `<goal>compile-custom</goal>` used? 

The documentation says:

> `protobuf:compile-custom` compiles main .proto definitions using a custom protoc plugin.

From my understanding this is used to call a custom protoc generator, eg, if a user wanted to make their own generator that parses, and generates, from proto files. 

Also, what does "compile" actually mean in this situation? Would a more correct work be transpile?

**Comment by sergei-ivanov** [comment]
`compile-custom` goal allows to use custom plugins with protoc (protobuf compiler). gRPC plugin is one of them. Basically, they are standalone executable files that are invoked by `protoc` and passed protobuf metadata that allows them to generate any custom output from proto files. For example, they may support generating protobuf bindings for exotic programming languages or generating alternative implementations. The prefix _compile_ is historic and relates to `protoc`, which stands for `protobuf compiler`.

**Comment by nobeh** [comment]
I had the same issue, you need to use 

```
<clearOutputDirectory>false</clearOutputDirectory>
```

as the default value is `true` which means before every goal execution, the generated source directory is cleaned. This is not an expected behavior in the case gRPC plugin.
