### ISSUE TITLE
There is no AARCH64 protoc on maven repo(Only for X86)

### ISSUE THREAD

**Issue by guyuqi** [xolstice/protobuf-maven-plugin#37]
Hi,
We want to compile the '.proto' file in our java project for Arm64 platform.
So the maven plugin: 'org.apache.maven.plugins' is a good choice: 
`       <plugin>

          <groupId>org.xolstice.maven.plugins</groupId>

          <artifactId>protobuf-maven-plugin</artifactId>

          <version>${protobuf.plugin.version}</version>

          <configuration>
            <protocArtifact>
                  com.google.protobuf:protoc:${external.protobuf.version}:exe:${os.detected.classifier}
              </protocArtifact>

            <protoSourceRoot>${basedir}/src/main/protobuf/</protoSourceRoot>

            <clearOutputDirectory>false</clearOutputDirectory>

            <checkStaleness>true</checkStaleness>

          </configuration>

`

 For the '**protocArtifact**',  only x86 protoc(exe)  is available in maven repo (https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/).

Do you have the plan to support other platforms like Arm?
（It means to offer binary executables for AArch64.）
Thanks!

**Comment by sergei-ivanov** [comment]
The binaries are built and deployed to Maven Central by the kind folks at Google. You have two options:
1. raise a ticket in https://github.com/google/protobuf project and kindly ask them to include AARCH64 binaries in the next release
2. build `protoc` binaries yourself and use other ways of specifying `protoc` location in the maven plugin configuration (`protocArtifact` won't work in your case)

**Comment by guyuqi** [comment]
Ok，I'll do it,thanks!
