### ISSUE TITLE
Generated java code generated by grpc connector have many errors in OuterClass and won't compile

### ISSUE THREAD

**Issue by onnorh** [xolstice/protobuf-maven-plugin#39]
Generated java code generated by for connection to a grpc connector have many errors and won't compile

The constructor InvalidProtocolBufferException(IOException) is undefined, 
The field AbstractMessage.memoizedSize is not visible	, 
The method unwrapIOException() is undefined for the type InvalidProtocolBufferException,

Can someone help?

[grpcconnectortest.zip](https://github.com/xolstice/protobuf-maven-plugin/files/1565286/grpcconnectortest.zip)

**Comment by sergei-ivanov** [comment]
The attached project does not build (unsatisfied dependencies). Can you please reduce it to a small sample project without any unnecessary dependencies that demonstrates the problem? A little co-operation on your part will be much appreciated.
