### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by daniel-shuy** [xolstice/protobuf-maven-plugin#46]
**Is your feature request related to a problem? Please describe.**
There are no Release Notes (at least not that I know of). This makes it difficult to know what has changed in a new version without looking into the source code itself.

**Describe the solution you'd like**
Release Notes, either on GitHub itself or in the Wiki. If it already exists, a link to it in the README or Wiki would be nice.

**Comment by sergei-ivanov** [comment]
I usually post updates on the top-level web site, e.g. [like this](https://www.xolstice.org/protobuf-maven-plugin-0.6.1-released/). There is also a detailed [change log](https://www.xolstice.org/protobuf-maven-plugin/changes-report.html) report on the generated Maven site. I guess I can add a link to the latter to the README file.

**Comment by daniel-shuy** [comment]
I see, that would be great, thanks!
