### ISSUE TITLE
Set clearOutputDirectory parameter to false by default

### ISSUE THREAD

**Issue by sergei-ivanov** [xolstice/protobuf-maven-plugin#48]
**Is your feature request related to a problem? Please describe.**

This is a legacy parameter that was introduced to work around problems with old (before 2.5.0) versions of `protoc`. It was set to `true` by default to force clearing out the target directory before invoking `protoc`. However, these days it is a common source of problems for users who run multiple code generations within a single build (for example, generate protobuf bindings and gRPC bindings). In those cases the subsequent executions clear out the output of the preceding executions.

**Describe the solution you'd like**

Set the default value for `clearOutputDirectory` parameter to `false`, so that it does not always have to be overridden.

**Describe alternatives you've considered**

Leave everything as is. But it's not a great option from the support perspective.

**Additional context**

N/A

**Comment by ananta-code** [comment]
even though it is false by default i am getting error "unable to clean up temporary proto file directory"  intermittently .
could you please guide me
