### ISSUE TITLE
Use lite code generation

### ISSUE THREAD

**Issue by hpehl** [xolstice/protobuf-maven-plugin#64]
I'm looking for a way to use the [lite](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md) variant when generating the Java source code. According to the documentation one has to use something like 

```
protoc --java_out=lite:${OUTPUT_DIR} path/to/your/proto/file
```

I'm wondering whether and how this can be used by the protobuf-maven-plugin. Using 

```
<plugin>
    <groupId>org.xolstice.maven.plugins</groupId>
    <artifactId>protobuf-maven-plugin</artifactId>
    <configuration>
        ...
        <outputDirectory>
            lite:${project.build.directory}/generated-sources/protobuf/java
        </outputDirectory>
    </configuration>
</plugin>
```

does not work.

**Comment by sergei-ivanov** [comment]
Looks like I need to port `javaScriptOptions` behaviour to `compile` mojo. Or make it a generic behaviour for all mojos. This way of configuring the output parameters was only supported by a couple of `protoc` output targets historically, but now seems to be more commonplace.

**Comment by stuffandthings** [comment]
@hpehl were you able to find a workaround? Finding myself wanting to generate `lite` variant code with maven as well.

**Comment by hpehl** [comment]
@stuffandthings Unfortunately no. I'm stuck right now.
