### ISSUE TITLE
Is there any way to configure output location for generated java files?

### ISSUE THREAD

**Issue by asif31iqbal** [xolstice/protobuf-maven-plugin#7]
I see that it is always generating the output java files inside the target folder. How can I configure it to generate those files inside the src/main/java folder, so that those files can stay alongside other existing source files?

**Comment by sergei-ivanov** [comment]
Yes, there is, and it is also in the documentation:
https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#outputDirectory

However, I do actively discourage you from mixing your sources under version control and generated sources. The whole purpose of this plugin is to do away with checking generated sources into VCS. Again, you are welcome to Gitter chat: I can probably suggest a better set-up for your project.

**Comment by asif31iqbal** [comment]
Thanks. I will try to get in touch in jitter.
