### ISSUE TITLE
Protobuf compiler removes __init__.py when compiling python

### ISSUE THREAD

**Issue by dtracers** [xolstice/protobuf-maven-plugin#9]
I am compiling the protobuf code to a source directory but it removes the **init**.py every single time.

It would be awesome if there was a parameter to have it not delete **init**.py for python.

**Comment by sergei-ivanov** [comment]
I would generally advise against compiling into source directory (and storing generated files under version control). But nevertheless, you may try setting [clearOutputDirectory](https://www.xolstice.org/protobuf-maven-plugin/compile-python-mojo.html#clearOutputDirectory) parameter to `false` in plugin configuration. It is `true` by default because of backward compatibility.

**Comment by dtracers** [comment]
That directory is ignored by version control.

My preference would be to compile to temp then copy to directory but maven
has a really hard time copying reliably.

What would be best practice of where to compile the python but then being
able to immediately import it from src tree?

**Comment by sergei-ivanov** [comment]
Obviously, Python is not a first class citizen in the Maven universe, and I don't know if there're any best practices with regard to generating and distributing Python sources from a Maven build.

Would you be able to share the set-up for your Maven project (feel free to remove/obfuscate any organisation-specific parts)? Maybe a gist with a stripped-down version to demonstrate the source tree layout and POM configuration.

**Comment by dtracers** [comment]
https://github.com/DonaldMcRonald/SketchRecognitionWithTensorFlow/blob/master/pom.xml

Here is the pom.

I get proto files from two places.  Another library (that also uses the same protobuf plugin so I can't put the **init**.py form their)  And the plugin itself.

Here is where the files are added
https://github.com/DonaldMcRonald/SketchRecognitionWithTensorFlow/tree/master/src/main/python/generated_proto

notice that the **init**.py is in version control but non of the genereted files are.  (I put it in vc so it is easier to add it back and notice when it is gone)

Here is the library that the first set of proto files are grabbed from.
https://github.com/dtracers/SketchRecognitionFramework/blob/master/pom.xml

Its smaller and is much easier to read

**Comment by sergei-ivanov** [comment]
I think I've got an idea of what you are trying to achieve.

I suggest that you do the following:
1. Add `<clearOutputDirectory>false</clearOutputDirectory>` configuration parameter to the `compile-python` execution. That will suppress automatic clearing out of the `generated_proto` directory by `protobuf-maven-plugin`.
2. Add a separate execution of `maven-clean-plugin`, bound to the `clean` phase, which will clear out everything but `__init__.py` from the `generated_proto` directory when you run `mvn clean` goal. See [here](http://maven.apache.org/plugins/maven-clean-plugin/clean-mojo.html#filesets) and [here](http://maven.apache.org/plugins/maven-clean-plugin/clean-mojo.html#excludeDefaultDirectories) for inspiration.
3. And it's probably a good time to ditch `protoc-plugin-default` and `protoc-plugin-backup` repository definitions from the POM: they are legacy.

**Comment by sergei-ivanov** [comment]
BTW, the above suggestion applies to both projects, only that `maven-clean-plugin` configuration for `SketchRecognitionFramework` will be simpler: it will simply blitz the entire `generated_proto` directory.

**Comment by dtracers** [comment]
Thank you that was exactly what I needed!
